### ISSUE TITLE
Assessing performance of TinyLlama

### ISSUE THREAD

**Issue by galleon** [jzhang38/TinyLlama#101]
I think it would be good to see how the performance of TinyLlama & TinyLlama-chat evolve over the checkpoint.
We can have this through the HL leaderboard but it is quite long.

What would you suggest to use as a benchmark to compare TinyLlama between versions ?

**Comment by jzhang38** [comment]
We have inlcuded the GPT4All benchmark results in EVAL.md

**Comment by jzhang38** [comment]
https://github.com/jzhang38/TinyLlama/blob/965a9de01fa217584bdb89cb05caa0b21729ec80/EVAL.md?plain=1#L30
