### ISSUE TITLE
如果我按中文语料CLM+SFT对TinyLlama进行重训，是否可行？

### ISSUE THREAD

**Issue by skykiseki** [jzhang38/TinyLlama#106]
好希望能有个TinyLlama-Chinese版本呀

**Comment by imanu20** [comment]
改变tokenizer就可以了

**Comment by ChaosCodes** [comment]
我们目前暂时还没有计划去训练一个中文版的 TinyLlama，但感觉可以先扩充词表然后混一半中文高质量的 corpus 基于现在的 TinyLLama 做 continual pretraining 来达到这个目标

**Comment by nghuyong** [comment]
We follow the tinyllama and train a 1.4B model for Chinese and English, named HammerLLM. You can check this model in https://github.com/Academic-Hammer/HammerLLM

**Comment by skykiseki** [comment]
> We follow the tinyllama and train a 1.4B model for Chinese and English, named HammerLLM. You can check this model in https://github.com/Academic-Hammer/HammerLLM

wow，excellent work！！！
