### ISSUE TITLE
Estimation of 2.5T Tokens Checkpoint

### ISSUE THREAD

**Issue by mounta11n** [jzhang38/TinyLlama#108]
Hello, do you have an estimation on when the 2.5T Tokens intermediate checkpoint will be ready?

Do you think you will achieve it before x-mas? I am very excited for next to release and can't wait heheh

Anyway, thank you so much for your work! You are contributing an extremely important part in this field!

**Comment by jzhang38** [comment]
https://huggingface.co/TinyLlama/TinyLlama-1.1B-intermediate-step-1195k-token-2.5T
Enjoy :)
