### ISSUE TITLE
The 4bit-quantized TinyLlama-1.1B's weight only takes up 550MB RAM ?

### ISSUE THREAD

**Issue by TapendraBaduwal** [jzhang38/TinyLlama#114]
After fine-tuning the model, I obtained a 2.2 GB PyTorch model.bin file. Is it possible to reduce this model size to 550 MB, and if so, how and when can we achieve this?

**Comment by RonanKMcGovern** [comment]
You fined tuned a quantized model or the original model?

Probably you fined tuned the original model so now you need to quantized.

Go to the llama.cpp repo and find the quantize folder. Find some Youtube videos if you need help.

**Comment by jzhang38** [comment]
It actually takes up around 700MB RAM on my Mac (using llama.cpp)

**Comment by TapendraBaduwal** [comment]
@jzhang38 After finetune model model_name = "TinyLlama/TinyLlama-1.1B-python-v0.1" on my own dataset with lora and SFTTrainer i got model size 2.05 , is this model size take 600-700 MB or how can we reduce model size upto 600-700MB ?
![Screenshot from 2023-12-24 12-13-22](https://github.com/jzhang38/TinyLlama/assets/87867535/66c81f49-3ef4-4705-b417-1cc43879bcb6)

**Comment by jzhang38** [comment]
@TapendraBaduwal You can checkout llama.cpp

**Comment by TapendraBaduwal** [comment]
@jzhang38 Thank you . Also  how can i apply best practice to continue training after loading from a lora checkpoint ?
I want to train lora checkpoint adapter continue training with new dataset.

**Comment by jzhang38** [comment]
@TapendraBaduwal I recommend you to check https://github.com/OpenAccess-AI-Collective/axolotl
