### ISSUE TITLE
Why change the `_init_weights` ?

### ISSUE THREAD

**Issue by larrylawl** [jzhang38/TinyLlama#117]
Hi, I noticed that the team changed the `_init_weights` function in this commit: https://github.com/jzhang38/TinyLlama/commit/89c75f40ec99cb48ea94c92423c1deae67bc2329

Can I check the motivation for doing so? Thanks!

**Comment by jzhang38** [comment]
Ah, this should not affect the behavior of initialization. 
https://github.com/jzhang38/TinyLlama/blob/b4964afba313499e5e6e15e8573c7648982c8896/lit_gpt/model.py#L306-L318
I did this so I could disable the swiglu while maintaining the init behaviors.

**Comment by jzhang38** [comment]
The previous implementation only scales the MLP output during init. We follow the init methods of https://github.com/kingoflolz/mesh-transformer-jax to also scale the attention output.

**Comment by larrylawl** [comment]
Thanks Peiyuan for replying!

Can I clarify why is this change made? When I printed the `module.weight.size(1)` of linear layers, they vary: they can either be `n_embd` or `intermediate_size`. Given that the `small_init` scheme is a function of the dimension, shouldn't it be `module.weight.size(1)` instead of `n_embd`?

<img width="408" alt="image" src="https://github.com/jzhang38/TinyLlama/assets/40198156/28058441-6891-45d6-851f-d3c6b7328dbb">

<img width="357" alt="image" src="https://github.com/jzhang38/TinyLlama/assets/40198156/97161ea7-bda8-4970-9bac-97ceb387c051">

For the following line, shouldn't the numerator be 2 instead of 1?

https://github.com/jzhang38/TinyLlama/blob/b4964afba313499e5e6e15e8573c7648982c8896/lit_gpt/model.py#L54

<img width="359" alt="image" src="https://github.com/jzhang38/TinyLlama/assets/40198156/0d02f4a4-04e1-4759-bf5a-02ff72bca5c8">

> We decide to follow the init methods of https://github.com/kingoflolz/mesh-transformer-jax to also scale the attention output.

Sorry peiyuan, can you point me to the code which implemented this? I can't seem to find it.

**Comment by larrylawl** [comment]
Bump jicymi @jzhang38

**Comment by jzhang38** [comment]
> For the following line, shouldn't the numerator be 2 instead of 1?

GPT-Neo X uses parallel attention and FF layer, and its section 2.1.3 says "with the factor of 2 compensating for the fact that the parallel and feed-forward layers are organized in parallel". Since Llama use sequential attention & FF, the numerator should be 1. 

>When I printed the module.weight.size(1) in the elif isinstance(module, nn.Linear) block, they vary: they can either be n_embd or intermediate_size. Given that the small_init scheme is a function of the dimension, shouldn't it be module.weight.size(1) instead of n_embd?

This is a really good question. I have the same doubts as you. In the end, I decided to follow the implementation of GPT-Neo X, where they use the n_embd value instead of weight.size(1). 
https://github.com/EleutherAI/gpt-neox/blob/f14782a571b9b4ff52803ce57c2bfc650670c30a/megatron/model/init_functions.py#L204

**Comment by larrylawl** [comment]
No worries at all. Thanks Peiyuan!
