### ISSUE TITLE
Have you considered code llama?

### ISSUE THREAD

**Issue by IgorTodorovskiIBM** [jzhang38/TinyLlama#12]
With https://github.com/KillianLucas/open-interpreter gaining steam, it would be cool if you can do a similar project with Code LLaMa

**Comment by Green-Sky** [comment]
1. the project you linked already works with code llama. :sweat_smile: 
2. not sure why you ask for code llama in this repo. :thinking:

**Comment by IgorTodorovskiIBM** [comment]
Ah ok, I see it's trained with the starcoderdata dataset. It would be interesting to try it with a project like open-interpreter and compare the performance with Code LLaMa

**Comment by VatsaDev** [comment]
A 'tinyCodeLlama' and integration with a similar tool could be possible, but we won't know for sure until the finetuning script comes out

**Comment by jzhang38** [comment]
The training mix already contains a significant portion (30%) of code. We plan to fine-tune TinyLlama into a model family (TinyLlama-Chat, TinyLlama-Chat-16k, TinyLlama-Code, ...) once the pretraining is done.

**Comment by TapendraBaduwal** [comment]
@jzhang38 Can we Finetuning using BitsandBytes and SFT ?

How we can train the model ?

**Comment by VatsaDev** [comment]
SFT is now possible @IgorTodorovskiIBM making a tinycodeLlama project is feasible, check SFT

**Comment by jzhang38** [comment]
There are many wonderful FT scripts out there. https://github.com/lm-sys/FastChat https://github.com/imoneoi/openchat. What I give is just a bare minimum. I actually encourage you to use those scripts instead of mine.
