### ISSUE TITLE
Full fine-tuning with llama.cpp

### ISSUE THREAD

**Issue by RonanKMcGovern** [jzhang38/TinyLlama#120]
When using GGUF and llama.cpp, is there a specific vocab file I should use, or can I use "ggml-vocab-llama.gguf"?

The number of kv groups is different in TinyLlama so I suspect that I need to use a custom vocab file, but I'm unsure.

I've been trying to fine-tune but the model isn't loading correctly. I've posted the training script on the llama.cpp repo [here](https://github.com/ggerganov/llama.cpp/issues/4703).

**Comment by jzhang38** [comment]
The vocab file should be the same as Llama. KV groups do not impact the tokenizer.
