### ISSUE TITLE
是否可以公布多一些checkpoint？

### ISSUE THREAD

**Issue by yangsp5** [jzhang38/TinyLlama#121]
鉴于现在对checkpoint的研究较少，是否可以每隔100B tokens公布一个checkpoint，方便大家研究模型的变化呢？

**Comment by jzhang38** [comment]
https://huggingface.co/TinyLlama/tinyLlama-intermediate-checkpoints
https://huggingface.co/TinyLlama/tinyLlama-intermediate-checkpoints-after-1T-token
