### ISSUE TITLE
TinyMix (Not Issue)

### ISSUE THREAD

**Issue by nivibilla** [jzhang38/TinyLlama#122]
Thanks for this amazing project. Using the experimental Mixtral branch of mergekit, I was able to MoE-ify the chat version of TinyLlama to make [TinyMix-8x1b-chat](https://huggingface.co/eastwind/tinymix-8x1b-chat)

Since it's rumoured that Mixtral was trained by upscaling mistral, tinymix is my attempt at the starting point of making a. Scaled down version of Mixtral.

Once again, appreciate the work on this project and looking forward to what's next!

**Comment by ChaosCodes** [comment]
Thank you for your interest. Since Mixtral has been release, we are also interested in building a TinyLlama MoE, which seems an awesome work. Good luck to you!
