### ISSUE TITLE
Loss logs

### ISSUE THREAD

**Issue by borgr** [jzhang38/TinyLlama#126]
Hey,
Do you have the train\eval loss\ performance during training (I see the checkpoints ones, but wondered if you also had more frequently sampled data throughout training).
Thanks

**Comment by jzhang38** [comment]
We have the eval plots throughout training here: https://arxiv.org/abs/2401.02385
The training loss can be found https://wandb.ai/lance777/lightning_logs/reports/metric-train_loss-23-09-04-23-38-15---Vmlldzo1MzA4MzIw?accessToken=5eu2sndit2mo6eqls8h38sklcgfwt660ek1f2czlgtqjv2c6tida47qm1oty8ik9

**Comment by borgr** [comment]
Trying to extract it, are you sure there isn't a way you can save me the hassle of extracting it manually from graphs? It is mush less reliable
