### ISSUE TITLE
Usage documentation

### ISSUE THREAD

**Issue by simensandhaug** [jzhang38/TinyLlama#129]
Was trying to use this but running script.sh didnt work after downloading requirements in a venv. Also tried running chat_gradio but gradio package was not even in requirements. Worked after i pip installed it separately but got an error after trying to chat. This really needs some usage documentation.

**Comment by hunter-lee1** [comment]
We have updated it to address these issues in chat_gradio. You can also try the new version on Google Colab [tinyllama-gradio](https://colab.research.google.com/drive/1qAuL5wTIa-USaNBu8DH35KQtICTnuLsy?usp=sharing)
