### ISSUE TITLE
How to train model with databricks-dolly-15k.jsonl dataset format.

### ISSUE THREAD

**Issue by TapendraBaduwal** [jzhang38/TinyLlama#13]
How to train model with databricks-dolly-15k.jsonl dataset format.

Can we Finetuning using BitsandBytes and SFT ?

**Comment by abrdgrt** [comment]
..

**Comment by VatsaDev** [comment]
@TapendraBaduwal you should probably wait till the models fully trained and then ask for this, but there was a mention sft in one of the closed issues

**Comment by TapendraBaduwal** [comment]
@jzhang38 For fine-tune i am using Parameter-Efficient Fine-Tuning (PEFT) . PEFT supports the QLoRa method to fine-tune a small fraction of the LLM parameters with 4-bit quantization. By merge the adapter weights. It is the right way to fine-tune this tiny model ?
