### ISSUE TITLE
Saturation / epoch-accuracy plot

### ISSUE THREAD

**Issue by rasbt** [jzhang38/TinyLlama#132]
Thanks for sharing this awesome work (and the paper write-up)! I was wondering if you by chance have a plot similar to the one from the Pythia paper but for all 3 epochs. If so, that would be super interesting and intriguing.

<img width="518" alt="Pythia_saturation" src="https://github.com/jzhang38/TinyLlama/assets/5618407/1bf435d1-9025-43bc-9ab0-ecf81a8c9143">

**Comment by rasbt** [comment]
Thanks, I was a bit confused by this and thought this was something different. Figure 1 shows 3456 GPU hours for TinyLlama, which I assume is for 1 epoch? The 10^4 mark in Figure 2 would then correspond to ~3 epochs?

**Comment by jzhang38** [comment]
<img width="877" alt="Screenshot 2024-01-11 at 11 26 34 AM" src="https://github.com/jzhang38/TinyLlama/assets/42993249/9211c4a7-7680-4e85-835d-39381761ff5d">
So sorry about the confusion in the report... Yeah, we did not make it clear. It should be the time taken to reach 300B tokens.

**Comment by RonanKMcGovern** [comment]
> Thanks for sharing this awesome work (and the paper write-up)! I was wondering if you by chance have a plot similar to the one from the Pythia paper but for all 3 epochs. If so, that would be super interesting and intriguing.

@rasbt what's your takeaway when you consider the Pythia work combined with this TinyLlama work?

**Comment by rasbt** [comment]
Thanks for clarifying @jzhang38 . If I understand it correctly now, is the following a correct assumption?

<img width="222" alt="Screenshot 2024-01-11 at 10 13 38 AM" src="https://github.com/jzhang38/TinyLlama/assets/5618407/26f68c15-9812-4689-884b-6b759a885bba">





> @rasbt what's your takeaway when you consider the Pythia work combined with this TinyLlama work? 

It looks like there's definitely an improvement due to architecture changes and perhaps the dataset :)

**Comment by Green-Sky** [comment]
@rasbt you did not respect the log scaling of the x-axis.
