### ISSUE TITLE
How do I use these data sets to train new models?

### ISSUE THREAD

**Issue by win10ogod** [jzhang38/TinyLlama#139]
How do I use these data sets to train new models?
https://huggingface.co/datasets/Skywork/SkyPile-150B
https://huggingface.co/datasets/EleutherAI/proof-pile-2

**Comment by win10ogod** [comment]
@jzhang38 Can you provide a script? 
                     I'm a little confused on how to modify the script.

**Comment by ChaosCodes** [comment]
Hi we are working on these two datasets, will release the scripts when we finish.
