### ISSUE TITLE
[Question] Is pre-training with FP32 possible?

### ISSUE THREAD

**Issue by veritas9872** [jzhang38/TinyLlama#145]
Hello, I am currently trying out pre-training and I was curious if the data type used for pre-training could be configured from using `torch.bfloat16` to `torch.float32`.
I would like to try this out in some unstable phases of model pre-training where the extra precision might be useful.
I am aware that TF32 has been enabled in the repository, so I think that the training will not become too slow.
However, I was not able to find a configurable option for using FP32.
Is there a location where this can be done? If not, do I have to manually change the code manually to use FP32?
Many thanks in advance!

**Comment by ChaosCodes** [comment]
Hi, you can check [this](https://lightning.ai/docs/fabric/stable/api/fabric_args.html#precision) to enable the FP32 training.

**Comment by veritas9872** [comment]
Unfortunately, it still requires manual editing of the model because parts such as the rotary embedding expect BF16.
