### ISSUE TITLE
Hello, is this tokenizer using LLaMA’s Tokenizer or did you train it yourself?

### ISSUE THREAD

**Issue by chenhk-chn** [jzhang38/TinyLlama#148]
Hello, is this tokenizer using LLaMA’s Tokenizer or did you train it yourself?

**Comment by awaelchli** [comment]
It is using the Llama tokenizer. You can get it by downloading any llama checkpoint from huggingface and then the preprocessing will load it from that directory: https://github.com/jzhang38/TinyLlama/blob/main/PRETRAIN.md#tokenize-data.
