### ISSUE TITLE
Cleaned Notebook

### ISSUE THREAD

**Issue by VatsaDev** [jzhang38/TinyLlama#15]
Just a Cleaned Version of the Colab Notebook from #6 , as Its ~15 lines of very self explanatory code, with a couple comments already in it. I just Cleaned the empty cells at the bottom, and removed the large numbers of big headers not needed for a Notebook this size. 

https://colab.research.google.com/drive/1HOxyJVxo0NeVk8oidvR3dvouGBTYO60X?usp=sharing

**Comment by ChaosCodes** [comment]
Thank for pointing out the redundant code in the Code Notebook. I have retified and revised it.

**Comment by VatsaDev** [comment]
👍
