### ISSUE TITLE
Pre training Continue from TinyLlama-1.1B-intermediate-step-1431k-3T

### ISSUE THREAD

**Issue by dshah-inspird-dev** [jzhang38/TinyLlama#163]
I am reaching out regarding the TinyLlama-1.1B-intermediate-step-1431k-3T model checkpoint that I am currently using for my project on Hugging Face.

I have been utilizing the pretraining code for this model using TinyLlama and have successfully converted the checkpoint using the convert_hf_checkpoint.py script. Now, I am interested in continuing the pretraining process for my documents to perform domain adaptation.

However, to resume training from the existing checkpoint, I require the checkpoint file or .pt file for this specific model. I would greatly appreciate it if you could share this checkpoint file with me to facilitate the continuation of my training process.

Thank you very much for your assistance and support. Please let me know if there is any additional information or steps required from my end.

**Comment by ChaosCodes** [comment]
Hi, thanks for your interest! You can get the pt files from [here](https://huggingface.co/TinyLlama/tinyllama_intermediate_lit_checkpoints). We will upload the early ckpts later.
