### ISSUE TITLE
Are there any provided 4bit quant weights, or like a colab detailing quantization?

### ISSUE THREAD

**Issue by VatsaDev** [jzhang38/TinyLlama#17]
I've seen 4bit weights mentioned a lot, but I can't find any references to them

Where can I find the 4bit quant weights, or do I have to quantize them? If so, is there a colab notebook for the process or something like that?

**Comment by VatsaDev** [comment]
nvm, Found them on huggingface 

link ---> https://huggingface.co/Green-Sky/TinyLlama-1.1B-step-50K-105b-GGUF/tree/main

**Comment by Green-Sky** [comment]
keep in mind that those are GGUF converted files for llama.cpp
