### ISSUE TITLE
你好，我想问下TinyLlama进行指令微调的代码有吗？以及微调的template格式是什么样呢？

### ISSUE THREAD

**Issue by fang-siqi** [jzhang38/TinyLlama#193]
你好，我想问下TinyLlama进行指令微调的代码有吗？以及微调的template格式是什么样呢？最近我想对TinyLlama进行指令微调，但是找不到学习的代码。。

**Comment by ChaosCodes** [comment]
可以参考这个 https://github.com/jzhang38/TinyLlama/blob/main/sft/finetune.py
