### ISSUE TITLE
Support Chinese Language？

### ISSUE THREAD

**Issue by Johnson-yue** [jzhang38/TinyLlama#2]
how many chinese data in training？ Would you plan to support chinese language？

**Comment by jzhang38** [comment]
Thanks for the qn! We use SlimPajama + Starcoderdata. There might be a tiny portion of Chinese in the data mix but definitely not much.

We do not plan to support Chinese in the current pretraining phase as we set a small model size plus we have only limited compute. We might explore continue-pretraining in Chinese once the current pretraining is done.

**Comment by Johnson-yue** [comment]
thank you

**Comment by nghuyong** [comment]
We follow the tinyllama and train a 1.4B model for Chinese and English, named HammerLLM.  You can check this model in https://github.com/Academic-Hammer/HammerLLM
