### ISSUE TITLE
Has anyone used this code base for incremental pretraining of llama-2-7b?

### ISSUE THREAD

**Issue by s1ghhh** [jzhang38/TinyLlama#21]

**Comment by VatsaDev** [comment]
This codebase uses the Llama-2 architecture, and is trying to train a 1.1B model on slim-pajama and StarCoder
We don't have a way of finetuning Llama-2 official models here. 
The 1.1B model itself is not fully released, so there is no official finetuning script

**Comment by jzhang38** [comment]
@s1ghhh Actually you can. What you need to do is first convert the huggingface llama 2 weight to be compatible with the weight naming of this codebase. (This [script](https://github.com/jzhang38/TinyLlama/blob/main/scripts/convert_lit_checkpoint.py) converts weight to HF format and what you need to do is the other way around). Appreciate if someone can submit a PR for this.

**Comment by VatsaDev** [comment]
@jzhang38 is it currently possible to finetune any llama-2 architecture model weights, as long as you convert it to this repos weights and use the pretrain scripts?

**Comment by jzhang38** [comment]
I have not tried it but from a big picture, yes.
