### ISSUE TITLE
Why is tokenizer.model_max_length set to 1000000000000000019884624838656?

### ISSUE THREAD

**Issue by kevinhu** [jzhang38/TinyLlama#23]
See https://huggingface.co/PY007/TinyLlama-1.1B-step-50K-105b/blob/main/tokenizer_config.json#L22

**Comment by ChuXNobody** [comment]
不涉及模型基础开发，跟训练集挂钩的设定

**Comment by ChuXNobody** [comment]
> 不涉及模型基础开发，跟训练集挂钩的设定



> 不涉及模型训练参数，跟训练集挂钩的设定，获取max token

**Comment by ChuXNobody** [comment]
不涉及模型训练参数，跟训练集挂钩的设定，获取max token

**Comment by jzhang38** [comment]
It is also present in the llama 2 config: https://huggingface.co/meta-llama/Llama-2-7b-hf/blob/6fdf2e60f86ff2481f2241aaee459f85b5b0bbb9/tokenizer_config.json#L22. I guess it is present to be compatible with other HuggingFace tokenizer. You can safely ignore it.
