### ISSUE TITLE
国内模型镜像

### ISSUE THREAD

**Issue by Ma-Yongqiang** [jzhang38/TinyLlama#26]
非常有意思的工作，但是huggingface 最近总是连接超时，是否可以放一个国内可以下载的链接呢。

**Comment by VatsaDev** [comment]
The Model runs through Llama.cpp for GGUF files, available at https://huggingface.co/Green-Sky/TinyLlama-1.1B-step-50K-105b-GGUF/tree/main

theres also a vLLM colab, at https://colab.research.google.com/drive/1StFCIjMYt2GwOktHSY1D2aNxhxVR4W-e?usp=sharing

**Comment by jzhang38** [comment]
translation for OP's post: 
"Very interesting work, but HuggingFace has been timing out recently. Can you provide a link that can be downloaded in China?"

我不太清楚国内一般用什么平台，你有什么推荐吗？
I am not quite sure what platforms are commonly used in China. Do you have any recommendations?

**Comment by VatsaDev** [comment]
@jzhang38 Thanks, google translate gave me similar, but the exact, gave the best answer I could. I guess The Llama.cpp and vLLM parts are still Valid, but is there a link outside Huggingface?

**Comment by hjing100** [comment]
https://modelscope.cn/datasets没有相应的数据集，是否可以考虑放一个

**Comment by hjing100** [comment]
最近https://huggingface.co无法访问

**Comment by Green-Sky** [comment]
Depending on the license, torrents or ipfs might be an option.

**Comment by ChaosCodes** [comment]
Hello, @Ma-Yongqiang and @hjing100, I have uploaded the latest checkpoints to modelscope. You can now download them and have fun using the following links: https://www.modelscope.cn/models/chaoscodes/TinyLlama-1.1B-intermediate-step-240k-503b/ and https://www.modelscope.cn/models/chaoscodes/TinyLlama-1.1B-Chat-v0.1/.

**Comment by ChaosCodes** [comment]
Hello, @Ma-Yongqiang  and @hjing100 , I've uploaded the latest checkpoints to modelscope. You can now download them and have fun using the following links:
[TinyLlama-1.1B-intermediate-step-240k-503b](https://www.modelscope.cn/models/chaoscodes/TinyLlama-1.1B-intermediate-step-240k-503b/)
[TinyLlama-1.1B-Chat-v0.1](https://www.modelscope.cn/models/chaoscodes/TinyLlama-1.1B-Chat-v0.1/)

**Comment by Ma-Yongqiang** [comment]
thanks for your hard work ~ @ChaosCodes

**Comment by JerryDaHeLian** [comment]
> [https://modelscope.cn/datasets没有相应的数据集，是否可以考虑放一个](https://modelscope.cn/datasets%E6%B2%A1%E6%9C%89%E7%9B%B8%E5%BA%94%E7%9A%84%E6%95%B0%E6%8D%AE%E9%9B%86%EF%BC%8C%E6%98%AF%E5%90%A6%E5%8F%AF%E4%BB%A5%E8%80%83%E8%99%91%E6%94%BE%E4%B8%80%E4%B8%AA)

严重支持！
