### ISSUE TITLE
Minimum learning rate

### ISSUE THREAD

**Issue by artnoage** [jzhang38/TinyLlama#27]
The minimum learning rate is the same as the "max". Is this intentional or a mistake? If yes, why (you can skip explanation if it is too bothersome)?

**Comment by jzhang38** [comment]
This is a **mistake** made by us and thanks a million for spotting that out!
Fortunately, we are still at the very early stage of training and there is still room to correct it. I have corrected this mistake, and the TinyLlama's lr curve will look like below:
![image](https://github.com/jzhang38/TinyLlama/assets/42993249/a7871be8-cf52-4414-b15c-5da126d9ba77)
