### ISSUE TITLE
Hardware requirements

### ISSUE THREAD

**Issue by ajinkya123-robo** [jzhang38/TinyLlama#3]
Hello, It's a very nice and much needed development. How much storage will be required for complete model training. As around 1.9TB is required only for datasets. Also how much RAM is required.
Best wishes to the team!

**Comment by jzhang38** [comment]
“How much storage will be required for complete model training” -> I estimate that 4TB disk is enough, provided you do not save checkpoints very frequently.
"Also how much RAM is required" -> I do not have a reasonable estimate for that. I am training on two DGX nodes. I guess a normal workstation with 8 * 4090/3090/A100 should always have enough RAM to perform this training.

**Comment by ajinkya123-robo** [comment]
Thank you!
