### ISSUE TITLE
Request: Finetune the Model on more Data?

### ISSUE THREAD

**Issue by VatsaDev** [jzhang38/TinyLlama#31]
This might be unorthodox, but I had to ask.

I've been trying to run the sft script on colab T4, and on Kaggle double T4, P100 and It [instantly ran out of memory](https://colab.research.google.com/drive/14DHAQwjyLXF_22cvLL9mUu0yc_IoyORE?usp=sharing). 
I've been Trying to perform a [QLora run](https://colab.research.google.com/drive/1ut1rCdA1LyLAw2Iq_C1yuZkHFUi0Gp8J?usp=sharing), and It was successful for a very small dataset, but the dataset I'm trying to finetune this with is around 20GB, and takes anywhere from 81 to 135 hrs to map, trying to stream the dataset makes it load nothing, and I can't run any CPU or GPU instances that long. 

If the SFT script isn't meant to take up that much memory, could you please fix it?    
If it is meant to use that much memory, I would like to request that you train a checkpoint or the final model on the [UnagamiData dataset](https://huggingface.co/datasets/VatsaDev/UnagamiData)

Its the dataset I used to train my previous model, [Unagami](https://github.com/VatsaDev/unagami). Its a Mixture of several high quality Datasets, Including Open-Platypus, Oasst1, and OpenOrca. It also has some QA from context datasets, like Dolly DataBricks, etc, which could make it better for RAG. 

Its currently Formatted with HTML-like tokens, like `<system>, <human>` I can switch to `### System: , ### Human:` if needed.    

Considerable?

**Comment by jzhang38** [comment]
We currently do not have that plan.
