### ISSUE TITLE
info when load model

### ISSUE THREAD

**Issue by shyoulala** [jzhang38/TinyLlama#34]
hi,when I load the model for train:
model = AutoModelForCausalLM.from_pretrained(
                model_name_or_path,
                torch_dtype=torch.bfloat16,
                # device_map="auto",
                trust_remote_code=True,
            )

info like this:(is it right?)
Some weights of LlamaForCausalLM were not initialized from the model checkpoint at /root/bert_path/TinyLlama-1.1B-intermediate-step-240k-503b/TinyLlama-1.1B-intermediate-step-240k-503b and are newly initialized: ['model.layers.18.self_attn.rotary_emb.inv_freq', 'model.layers.21.self_attn.rotary_emb.inv_freq', 'model.layers.19.self_attn.rotary_emb.inv_freq', 'model.layers.9.self_attn.rotary_emb.inv_freq', 'model.layers.10.self_attn.rotary_emb.inv_freq', 'model.layers.20.self_attn.rotary_emb.inv_freq', 'model.layers.0.self_attn.rotary_emb.inv_freq', 'model.layers.11.self_attn.rotary_emb.inv_freq', 'model.layers.7.self_attn.rotary_emb.inv_freq', 'model.layers.15.self_attn.rotary_emb.inv_freq', 'model.layers.4.self_attn.rotary_emb.inv_freq', 'model.layers.16.self_attn.rotary_emb.inv_freq', 'model.layers.5.self_attn.rotary_emb.inv_freq', 'model.layers.1.self_attn.rotary_emb.inv_freq', 'model.layers.14.self_attn.rotary_emb.inv_freq', 'model.layers.3.self_attn.rotary_emb.inv_freq', 'model.layers.6.self_attn.rotary_emb.inv_freq', 'model.layers.13.self_attn.rotary_emb.inv_freq', 'model.layers.2.self_attn.rotary_emb.inv_freq', 'model.layers.12.self_attn.rotary_emb.inv_freq', 'model.layers.8.self_attn.rotary_emb.inv_freq', 'model.layers.17.self_attn.rotary_emb.inv_freq']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

**Comment by VatsaDev** [comment]
`AutoModelForCausalLM` is a huggingface based library, and from what a simple google search tells me, this is [super common](https://www.google.com/search?q=Some+weights+of+LlamaForCausalLM+were+not+initialized+from+the+model+checkpoint+at+%2Froot%2Fbert_path%2FTinyLlama-1.1B-intermediate-step-240k-503b%2FTinyLlama-1.1B-intermediate-step-240k-503b+and+are+newly+initialized%3A&rlz=1C5CHFA_enUS1062US1064&oq=Some+weights+of+LlamaForCausalLM+were+not+initialized+from+the+model+checkpoint+at+%2Froot%2Fbert_path%2FTinyLlama-1.1B-intermediate-step-240k-503b%2FTinyLlama-1.1B-intermediate-step-240k-503b+and+are+newly+initialized%3A&gs_lcrp=EgZjaHJvbWUyBggAEEUYOdIBBzQ2NWowajeoAgCwAgA&sourceid=chrome&ie=UTF-8&scrlybrkr=4c9c022b&safe=active&ssui=on)

This is just a warning, as quoted by the repo

> This is expected, and tells you that you won't have good performance with your model before you fine-tune it.

Does finetuning give you any errors?

**Comment by VatsaDev** [comment]
Also 

```py
from transformers import logging

logging.set_verbosity_warning()
```

**Comment by jzhang38** [comment]
@shyoulala  You can safely ignore this warning, including "You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference".
