### ISSUE TITLE
TinyLlama-1.1B-orca-gpt4

### ISSUE THREAD

**Issue by acalatrava** [jzhang38/TinyLlama#35]
First, I want to express my gratitude about this project. I think TinyLlama has a lot of potential and we're just starting to see it. Cudos!

I'm pretty new to this exciting field and this is the first time I fine-tuned a model. I used the "base" TinyLlama model (step-240k) to fine-tune using the [sam-mosaic/orca-gpt4-chatml](https://huggingface.co/datasets/sam-mosaic/orca-gpt4-chatml) dataset but the result seems not as good as your v0.2 chat model. 

I will keep working on this and I will share with you the models I create. I think that the RAG approach you guys are experimenting now is the good direction and I'll going to do some experiments with that too.

Anyway the model I produced is here in case you want to take a look: [TinyLlama-1.1B-orca-gpt4](https://huggingface.co/acalatrava/TinyLlama-1.1B-orca-gpt4)

**Comment by jzhang38** [comment]
Hi acalatrava thanks for that! I will include your model into the EVAL.md later today.

You can try out this dataset https://huggingface.co/datasets/shahules786/orca-best. This is a filtered version of openorca and should produce better results.
