### ISSUE TITLE
Why is Swiglu packed_weights = False?

### ISSUE THREAD

**Issue by larrylawl** [jzhang38/TinyLlama#37]
Hi, can i check why did you set the Swiglu packed_weights to be False? From [this discussion](https://github.com/facebookresearch/xformers/issues/734), "you shouldn't set "_pack_weights=False" as it prevents from fusing a few kernels during the BW pass".

https://github.com/jzhang38/TinyLlama/blob/3cffb3cc933c9cb7aa7478f5ceb1e328141953c3/lit_gpt/model.py#L301

**Comment by jzhang38** [comment]
Hi Larry You are right. _pack_weights should be set to True by default. 
For me, I remember I ran two runs with and without _pack_weights and did not notice much difference in speed so I just set it to False so I don't need to deal with splitting the weight when converting the format into HF :).
