### ISSUE TITLE
Release format + artefact

### ISSUE THREAD

**Issue by PierreColombo** [jzhang38/TinyLlama#39]
Dear Authors,
Thanks so much for your amazing project. 
Would it be possible for you plan to release the following:
1. the optimizer states
2. the scheduler
3. a checkpoint just before cooling down the model

This would be a highly valuable artefact for keeping training the model !

Thanks so much and congratulation for your work !
Pierre

**Comment by jzhang38** [comment]
We will upload all intermediate checkpoints (one every 10B tokens) to HuggingFace and ModelScope soon. 

Once we finish uploading the model weights we will consider uploading the optimizer states.

**Comment by jzhang38** [comment]
All intermediate checkpoints is here: https://huggingface.co/TinyLlama/tinyLlama-intermediate-checkpoints/tree/step-480k-token-1007B
