### ISSUE TITLE
Question Regarding the Absence of BOS and EOS Tokens in Tokenizer Encoding

### ISSUE THREAD

**Issue by dtxwhzw** [jzhang38/TinyLlama#40]
I noticed that your tokenizer doesn't add the bos  and eos token to the final tensor during encoding. Does this have any impact on pretraining? If it's intentional not to add them, what is the reason behind it?

**Comment by jzhang38** [comment]
It does add sep token: https://github.com/jzhang38/TinyLlama/blob/3322601dd28788a64e6b2085d6870aa167b5a264/lit_gpt/packed_dataset.py#L95

**Comment by dtxwhzw** [comment]
> It does add sep token:
> 
> https://github.com/jzhang38/TinyLlama/blob/3322601dd28788a64e6b2085d6870aa167b5a264/lit_gpt/packed_dataset.py#L95

Since the self._idx starts from 0. I think all the bos token in the self._arr would be replaced by the input arr:
https://github.com/jzhang38/TinyLlama/blob/3322601dd28788a64e6b2085d6870aa167b5a264/lit_gpt/packed_dataset.py#L114
Secondly, it's confirmed that there is no EOS token, right?

**Comment by jzhang38** [comment]
Yes, your understanding is correct. I rechecked the actual code used for pretraining and I set the bos to True by default in the below line. So there is a sep token. 

https://github.com/jzhang38/TinyLlama/blob/3322601dd28788a64e6b2085d6870aa167b5a264/lit_gpt/tokenizer.py#L54

> Secondly, it's confirmed that there is no EOS token, right?

There is no EOS token.

**Comment by ZeguanXiao** [comment]
@jzhang38 In the current version, `bos` is False and `eos` is True, but prepare_*.py scripts use `bos` as sep token. Does this mean there is a bug?
https://github.com/jzhang38/TinyLlama/blob/bf122247c486b6b897050e98cbb7bedae8eeba73/lit_gpt/tokenizer.py#L55
