### ISSUE TITLE
Why is the vocab size of `TinyLlama-1.1B-Chat-V0.1` 32001?

### ISSUE THREAD

**Issue by Chillee** [jzhang38/TinyLlama#41]
Makes it somewhat more annoying to use.

Also, were there any changes in how the weights are saved between TinyLlama-1.1B-intermediate-step-240k-503b and TinyLlama-1.1B-intermediate-step-50k-105b? I'm getting incorrect output with the newer checkpoint for code that worked with the first checkpoint.

**Comment by jzhang38** [comment]
Thanks for your question.

> Why is the vocab size of TinyLlama-1.1B-Chat-V0.1 32001

We add a [PAD] token during FT.

> were there any changes in how the weights are saved between TinyLlama-1.1B-intermediate-step-240k-503b and TinyLlama-1.1B-intermediate-step-50k-105b?

No changes.

**Comment by Chillee** [comment]
I assume the `[PAD]` token is the last token in the embedding matrix? Can it be safely removed? 

For speculative decoding with say, llama, it just makes it a bit more inconvenient to align the token spaces.

**Comment by jzhang38** [comment]
> I assume the [PAD] token is the last token in the embedding matrix? Can it be safely removed?

Yes and Yes.

**Comment by jzhang38** [comment]
Closing this issue for now. Feel free to reopen if you have any other question.

**Comment by Chillee** [comment]
Still very mysterious, but the `TinyLlama-1.1B-intermediate-step-480k-1T` checkpoint works for me again.
