### ISSUE TITLE
How to compute token numbers for a dataset？

### ISSUE THREAD

**Issue by qiezikuangge** [jzhang38/TinyLlama#42]
Whether to use tokenizer to encode each sample and then calculate the total tokens？

**Comment by VatsaDev** [comment]
If you have the disk space to hold all the data, you could just tokenize the data, and get the length, get the token numbers.

If you have borderline disk space, streamload the files, tokenize the data in chunks, and then delete the array, while just adding the array length to a separate variable, and then having the total tokens.

If you have really, really low disk space, stream download the file, then tokenize the chunks as you download them, check the length, delete the chunk.

**Comment by qiezikuangge** [comment]
> If you have the disk space to hold all the data, you could just tokenize the data, and get the length, get the token numbers.
> 
> If you have borderline disk space, streamload the files, tokenize the data in chunks, and then delete the array, while just adding the array length to a separate variable, and then having the total tokens.
> 
> If you have really, really low disk space, stream download the file, then tokenize the chunks as you download them, check the length, delete the chunk.

For example, if I have a txt file that have 10 rows. Then I should use tokenizer encode every row, may every row be encoded 10 tokens, so the total tokens is $10\times 10=100$

**Comment by VatsaDev** [comment]
Basically yes, but keep in mind that the data is a JSONL file, so pull the content out of the json before tokenizing?

**Comment by JerryDaHeLian** [comment]
> Basically yes, but keep in mind that the data is a JSONL file, so pull the content out of the json before tokenizing?

I think so.
