### ISSUE TITLE
下载数据集不便

### ISSUE THREAD

**Issue by scorpjr1** [jzhang38/TinyLlama#44]
需要的数据集好大，而且还得科学上网下载的。不知道 大佬能不能提供一下下载数据集的网盘或者torrent之类的下载渠道？

**Comment by jzhang38** [comment]
我们最近会把所有中间checkpoint(每10B token一个）都上传到modelscope。 
暂时没有计划用网盘或者torrent host 数据集。

We will upload all intermediate checkpoints (one every 10B tokens) to ModelScope soon. We currently have no plans to use cloud drives or torrent hosts for the dataset.

**Comment by JerryDaHeLian** [comment]
在中国大陆，目前连不上huggingface，持续一个月左右了！
