### ISSUE TITLE
Any plans for the ONNX runtime?

### ISSUE THREAD

**Issue by VatsaDev** [jzhang38/TinyLlama#46]
One of your potential Usecases is to deploy on edge devices.

For that, the [ONNX runtime](https://onnxruntime.ai/) is probably the most likely candidate, supporting a lot of platforms/apis/architectures/hardware-accelerators.
Its supposably easy to convert any huggingface hosted models to ONNX with [optimum](https://huggingface.co/docs/optimum/index), though I haven't done it personally.

Any thoughts?

**Comment by jzhang38** [comment]
You can have a try.

**Comment by VatsaDev** [comment]
After trying to integrate to onnx with optimum, I have a ~working run, but it can't cache and overuses cpu ram, gonna need more work

**Comment by VatsaDev** [comment]
I've submitted an issue to the transformers.js repo for tinyLlama being added, closing this
