### ISSUE TITLE
Why train three epochs? not one epoch?

### ISSUE THREAD

**Issue by PeiqinSun** [jzhang38/TinyLlama#47]
Hi, Thanks for your great works!
In all previous works(i.e. GPTs, LLaMAs, ...), them both pretrain one epoch. But I found you train three epoch? why set three? 
Looking forward to hearing from you in your free time. Thank you very much.

**Comment by jzhang38** [comment]
It is not fair to say all previous works.

1. T5 is trained on multiple epochs.
2. Pythia-deduped is trained on 1.5 epochs. 
3. Some previous works studied repetition (https://arxiv.org/abs/2305.16264) and found no issue with that.
4. The intermediate checkpoints of TinyLlama can be artifacts for studying multi-epoch training.
