### ISSUE TITLE
Where dose the rotary_emb import come from?

### ISSUE THREAD

**Issue by nmharmon8** [jzhang38/TinyLlama#5]
Hi,

Where dose the ```import rotary_emb``` come from? I don't see it in the requirements, and a google search is not reveling a GitHub that follows this structure. 

Thanks,

**Comment by jzhang38** [comment]
git clone https://github.com/Dao-AILab/flash-attention
cd flash-attention
python setup.py install
cd csrc/rotary && pip install .

**Comment by nmharmon8** [comment]
Thank you.
