### ISSUE TITLE
python环境包有可能发出来一份吗

### ISSUE THREAD

**Issue by lightcome** [jzhang38/TinyLlama#54]
虽然它很基础，但确实很重要并且也很耗时，看着当前并非使用稳定版本，自己构建环境包遇到各种问题，目前会挂在xformer源码构建上，请问有可能发出来份python包链接吗？例如conda环境放到一个网盘上，感谢

**Comment by JerryDaHeLian** [comment]
同样需要安装xformer 不成功问题。具体到安装环境搭建时，执行如下命令：
pip install -v -U git+https://github.com/facebookresearch/xformers.git@main#egg=xformers
一直不成功。
中国国内连github 太不稳定了，很多包都下不了或者是下载途中中断。

**Comment by JerryDaHeLian** [comment]
谁有连接github 比较好的方法？

**Comment by ChaosCodes** [comment]
> pip install -v -U git+https://github.com/facebookresearch/xformers.git@main#egg=xformers

How about trying tsinghua mirrors via `pip install -i https://pypi.tuna.tsinghua.edu.cn/simple -v -U git+https://github.com/facebookresearch/xformers.git@main#egg=xformers`? 

Does it work?

**Comment by JerryDaHeLian** [comment]
> > pip install -v -U git+https://github.com/facebookresearch/xformers.git@main#egg=xformers
> 
> How about trying tsinghua mirrors via `pip install -i https://pypi.tuna.tsinghua.edu.cn/simple -v -U git+https://github.com/facebookresearch/xformers.git@main#egg=xformers`?
> 
> Does it work?

不行，我尝试过。

**Comment by jzhang38** [comment]
> 例如conda环境放到一个网盘上，感谢
建议挂梯子并且把环境需要的代码放到国内github平替上。
