### ISSUE TITLE
Problem with TinyLlama-1.1B-Chat-v0.3 tokenizer

### ISSUE THREAD

**Issue by galleon** [jzhang38/TinyLlama#56]
I am wondering if this behavior is correct:

```
from transformers import AutoTokenizer
tokenizer = AutoTokenizer.from_pretrained("PY007/TinyLlama-1.1B-Chat-v0.3")
print(f"vocab_size: {tokenizer.vocab_size}")
print(f"length get_vocab: {len(tokenizer.get_vocab())}")
print(list(vocab.keys())[list(vocab.values()).index(32000)])
print(list(vocab.keys())[list(vocab.values()).index(32001)])
print(list(vocab.keys())[list(vocab.values()).index(32002)])
```

```
Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
vocab_size: 32000
length get_vocab: 32003
[PAD]
<|im_start|>
<|im_end|>
```

I compared tokenizers from  `TinyLlama-1.1B` `TinyLlama-1.1B-Chat`  `Llama-2-7b-hf` and `Llama-2-7b-chat-hf` which are supposed to be the same and only `TinyLlama-1.1B-Chat` has this discrepancy.

**Comment by RonanKMcGovern** [comment]
Yeah that makes sense.

That chat model is mlchat format, which requires tokens to be added for start and end because they aren't in the base vocab.

**Comment by galleon** [comment]
Hmmm I understand the reasoning but then would expect "meta-llama/Llama-2-7b-chat-hf" to exhibit a similar behaviour with [INST] and [\INST] but it does not seem to be the case afaik:

```
tokenizer = AutoTokenizer.from_pretrained("meta-llama/Llama-2-7b-chat-hf")
print("[\INST]" in tokenizer.get_vocab())
print("[INST]" in tokenizer.get_vocab())
print(tokenizer.encode("<s>[INST]"))
print(tokenizer.encode(tokenizer._bos_token.content))
print(tokenizer.encode("</s>"))
```

I am also in the process in finetuning for the Llama 2 format still WIP.

PS: your link is broken ;-)

**Comment by VatsaDev** [comment]
Yep all of these tokens are meant to be here
 - ChatML format for the `im` tokens
 - The Authors of the Repo added the pad token themselves, theres another issue for the 32001 token len

**Comment by jzhang38** [comment]
We have updated the model weight/ft script. Now the bug should be fixed.
