### ISSUE TITLE
Converting Saved Model Files to Hugging Face Transformers Format

### ISSUE THREAD

**Issue by dtxwhzw** [jzhang38/TinyLlama#60]
Hello, I have been using your pre-trained code, and I'm wondering how to convert the saved model files into the Hugging Face Transformers format, similar to the ones you upload to Hugging Face's repository?

**Comment by ChaosCodes** [comment]
You can check this [scripts/convert_lit_checkpoint.py](https://github.com/jzhang38/TinyLlama/blob/main/scripts/convert_lit_checkpoint.py).
Run the following command to convert the model ckpt.
```shell
python scripts/convert_lit_checkpoint.py \
    --checkpoint_name your_checkpoint.pth \
    --out_dir destination_dir/ \
    --model_name tiny_LLaMA_1b
```

**Comment by Juhywcy** [comment]
@ChaosCodes sorry, I use the command to convert the model ckpt from .pth into .bin, but the param "out_dir" can't work. It is always saved in the same path as ckpt dir. How to solve this?
