### ISSUE TITLE
Replay Finetuning & store as GGML

### ISSUE THREAD

**Issue by galleon** [jzhang38/TinyLlama#63]
Hi

I have been trying to redo TinyLlama finetuning starting from `PY007/TinyLlama-1.1B-intermediate-step-480k-1T` using both [finetuning.py](https://github.com/jzhang38/TinyLlama/blob/main/sft/finetune.py) and using the last command from [script.sh](https://github.com/jzhang38/TinyLlama/blob/main/sft/script.sh).
I used one A100 40G (using only 27GB of VRAM). Everything went [well](https://wandb.ai/galleon/huggingface/runs/aqyumzy2?workspace=user-galleon) apparently.

I just added:
```
final_model="path to last checkpoint"

tokenizer = AutoTokenizer.from_pretrained(final_model)

model = model = AutoModelForCausalLM.from_pretrained(
        final_model,
        device_map="auto",
        trust_remote_code=True,
    )

model.save_pretrained("TinyLlama-1.1B-chat-hf")
tokenizer.save_pretrained("TinyLlama-1.1B-chat-hf")
```

Then I tried to convert the model to a GGML format using `convert.py` from `llama.cpp`

`!python convert.py <path to TinyLlama-1.1B-chat-hf>`

This lead to the following error:

```
Loading model file <path to TinyLlama-1.1B-chat-hf/pytorch_model.bin>
params = Params(n_vocab=32003, n_embd=2048, n_layer=22, n_ctx=2048, n_ff=5632, n_head=32, n_head_kv=4, f_norm_eps=1e-05, f_rope_freq_base=10000.0, f_rope_scale=None, ftype=None, path_model=PosixPath('/content/drive/MyDrive/TinyLlama/TinyLlama/sft/TinyLlama-1.1B-chat-hf'))
Loading vocab file '/content/drive/MyDrive/TinyLlama/TinyLlama/sft/TinyLlama-1.1B-chat-hf/tokenizer.model', type 'spm'
Traceback (most recent call last):
  File "/content/drive/MyDrive/TinyLlama/llama.cpp/convert.py", line 1193, in <module>
    main()
  File "/content/drive/MyDrive/TinyLlama/llama.cpp/convert.py", line 1175, in main
    vocab = load_vocab(vocab_dir, args.vocabtype)
  File "/content/drive/MyDrive/TinyLlama/llama.cpp/convert.py", line 1086, in load_vocab
    return SentencePieceVocab(path, added_tokens_path if added_tokens_path.exists() else None)
  File "/content/drive/MyDrive/TinyLlama/llama.cpp/convert.py", line 372, in __init__
    raise Exception(f"Expected added token IDs to be sequential and start at {len(added_tokens)}; got {actual_ids}")
Exception: Expected added token IDs to be sequential and start at 6; got [0, 1, 2, 32000, 32001, 32002]
```

Any idea what I am doing wrong ?

Some more info contained in related files:

_special_tokens_map.json_
```
{
  "additional_special_tokens": [
    "<unk>",
    "<s>",
    "</s>",
    "[PAD]",
    "<|im_end|>",
    "<|im_start|>"
  ],
  "bos_token": "<s>",
  "eos_token": "</s>",
  "pad_token": "[PAD]",
  "unk_token": "<unk>"
}
```

_added_tokens.json_
```
{
  "</s>": 2,
  "<s>": 1,
  "<unk>": 0,
  "<|im_end|>": 32001,
  "<|im_start|>": 32002,
  "[PAD]": 32000
}
```

Those files are slightly different from what can be found in `PY007/TinyLlama-1.1B-Chat-v0.3` and I don't understand why.

**Comment by ChaosCodes** [comment]
Hi, as for this bug, I think it is because that in [llama.cpp](https://github.com/ggerganov/llama.cpp/blob/master/convert.py#L370) they will find the tokens in `added_tokens.json` and put them into SentencePiece Vocabulary. However, because `</s>`, `<s>`, `<unk>` have already in the original vocabulary which comes from `tokenizer.model`, they will raise an error if the added tokens id does not start from `vocab_size`. You can rewrite the `added_token.json` as
```json
{
  "<|im_end|>": 32001,
  "<|im_start|>": 32002,
  "[PAD]": 32000
}
```

Perhaps it could work by this way? If there is still something wrong. I will test it tmr.
