### ISSUE TITLE
great work! can you do a mistral 1b tinyllama?

### ISSUE THREAD

**Issue by hiqsociety** [jzhang38/TinyLlama#65]
great work! can you do a mistral 1b tinyllama?
mistral ai is good.

**Comment by VatsaDev** [comment]
This Issue Doesn't really make sense? Are you talking about mistral architecture, like sliding window? The dataset for mistral is unreleased, and there are no comments on any parts of the dataset, other than the 8T rumor? Without a plan/details, this just comes across as mistral Hype.

**Comment by PhilippeFerreiraDeSousa** [comment]
Swapping Llama by Mistral means swapping architecture and tokenizer on same project dataset.

**Comment by RonanKMcGovern** [comment]
@PhilippeFerreiraDeSousa yeah good point.

I'm not a huge fan of mistral architecture. My sense is the reduced attention is lossy. Other than that it's not all that different than Llama, just a bit faster.

**Comment by hiqsociety** [comment]
@VatsaDev i just realised i like mistral so much (i use it more than the rest of the 7Bs). wasnt thinking clear. I thought someone can figure out how to shrink mistral to 1B or something.

anyway, I've tested tinyllama 1B and it's "great", hope to see the fixed version. current one has a lot of repetitions.
