### ISSUE TITLE
release of 1.5T checkpoint

### ISSUE THREAD

**Issue by sadransh** [jzhang38/TinyLlama#68]
Thanks for the great great work! 
Is there any plan on releasing the 1.5T checkpoint based on wandb the checkpoint should be saved, 

Is there any plan to release it today? @jzhang38

**Comment by TianduoWang** [comment]
Hi sadransh,

According to our original plan, the TinyLlama 1.5T checkpoints would be released on 2023-10-16. Unfortunately, a bug was identified and we plan to postpone the release of the 1.5T checkpoints. We have updated this information in our README and you may find more information about this bug in this [link](https://whimsical-aphid-86d.notion.site/Release-of-TinyLlama-1-5T-Checkpoints-Postponed-01b266998c1c47f78f5ae1520196d194?pvs=4).

**Comment by Green-Sky** [comment]
What happens to all the intermediate steps so far ? i can see until 1510B. will the be deleted/overwritten ?

**Comment by Green-Sky** [comment]
Looks like they will just be overwritten, is this intended?

**Comment by ChaosCodes** [comment]
> Looks like they will just be overwritten, is this intended?

Hi, we have uploaded the intermediate checkpoints so far (they are not overwritten now), but we are still considering how to deal with the checkpoint for 1T to 1.5T.
