### ISSUE TITLE
How to get the huggingface format model and config?

### ISSUE THREAD

**Issue by SinclairCoder** [jzhang38/TinyLlama#73]
Thanks for your great work.

I converted the model from  `.pth` type to `.bin` type via the  `convert_lit_checkpoint.py` script. But I found there is no config file converted. Could you mind share the complete script to help the converting process? Thanks.

![image](https://github.com/jzhang38/TinyLlama/assets/46218454/01d6f78f-456d-47a3-8ca6-47c25f8eeaed)

![image](https://github.com/jzhang38/TinyLlama/assets/46218454/3189bfe1-5515-437e-a652-1b4dde447cf6)

**Comment by SinclairCoder** [comment]
Thanks for your reply. I gradually realised this. Hope there will be a better solution, especially if some config needs to be modified.

**Comment by JerryDaHeLian** [comment]
> I manually fill out the correct HF model config for TinyLlama. For the other files, I simply use those from llama-2-HF.

Can you give me a config.json file ? Or give me the content of the config.json file ?

**Comment by SinclairCoder** [comment]
Here is my solution.

```python
def lit_to_hf_model_config_mapping(lit_config_dict):
    hf_config_dict = {}
    for k, v in lit_config_dict.items():
        if key == "padded_vocab_size":
            hf_config_dict["vocab_size"] = v
        elif key == "n_embd":
            hf_config_dict["hidden_size"] = v
        elif key == "n_layer":
            hf_config_dict["num_hidden_layers"] = v
        elif key == "n_head":
            hf_config_dict["num_attention_heads"] = v
        elif key == "n_query_groups":
            hf_config_dict["num_key_value_heads"] = v
        elif key == 'bias':
            hf_config_dict['attention_bias'] = v
        elif key == 'org':
            continue
        else:
            hf_config_dict[key] = v
    
    hf_config_dict['max_position_embeddings'] = hf_config_dict['block_size']
    hf_config_dict['tie_word_embeddings'] = False
    # ROPE TODO
    # hf_config_dict['rope_theta'] = 10000.0

    # hidden_act TODO swiglu

    return hf_config_dict

# xxxx some other code

if fabric.global_rank == 0:
    config_dict = lit_to_hf_model_config_mapping(asdict(model.config))
    config_path = args.out_dir / "config.json"
    fabric.print(f"Saving model config file to {str(config_path)!r}")
    with open(config_path, "w") as f:
        json.dump(config_dict, f, indent=4)
```

**Comment by JerryDaHeLian** [comment]
> Here is my solution.
> 
> ```python
> def lit_to_hf_model_config_mapping(lit_config_dict):
>     hf_config_dict = {}
>     for k, v in lit_config_dict.items():
>         if key == "padded_vocab_size":
>             hf_config_dict["vocab_size"] = v
>         elif key == "n_embd":
>             hf_config_dict["hidden_size"] = v
>         elif key == "n_layer":
>             hf_config_dict["num_hidden_layers"] = v
>         elif key == "n_head":
>             hf_config_dict["num_attention_heads"] = v
>         elif key == "n_query_groups":
>             hf_config_dict["num_key_value_heads"] = v
>         elif key == 'bias':
>             hf_config_dict['attention_bias'] = v
>         elif key == 'org':
>             continue
>         else:
>             hf_config_dict[key] = v
>     
>     hf_config_dict['max_position_embeddings'] = hf_config_dict['block_size']
>     hf_config_dict['tie_word_embeddings'] = False
>     # ROPE TODO
>     # hf_config_dict['rope_theta'] = 10000.0
> 
>     # hidden_act TODO swiglu
> 
>     return hf_config_dict
> 
> # xxxx some other code
> 
> if fabric.global_rank == 0:
>     config_dict = lit_to_hf_model_config_mapping(asdict(model.config))
>     config_path = args.out_dir / "config.json"
>     fabric.print(f"Saving model config file to {str(config_path)!r}")
>     with open(config_path, "w") as f:
>         json.dump(config_dict, f, indent=4)
> ```

Thanks, I will try.

**Comment by TianduoWang** [comment]
Hi all,

We have added this function into "scripts/convert_lit_checkpoint.py". If you want to convert the config file, just add "--model_only False" before running the script.
