### ISSUE TITLE
A question about Dataset combination

### ISSUE THREAD

**Issue by PeiqinSun** [jzhang38/TinyLlama#75]
In tinyllama, the dataset is combine of  Slimpajama & Starcoderdata, the total tokens in dataset is around 950B tokens; 
My question is: what's the meaning of `Sampled all code from Starcoderdata`? It's mean that only samples the program code tokens(exclude github issue and jupyter notebook), or includes all tokens in Starcoderdata?
Looking forward to hearing from you in your free time. Thank you very much.

**Comment by ChaosCodes** [comment]
Hi! Some of the data in Slimpajama originates from GitHub. To avoid potential overlaps with data in Starcoderdata, we've removed those GitHub-related data in Slimpajama and only used code data from Starcoderdata during pre-training. `Sampled all code from Starcoderdata` means that all code data we used in pre-training is sampled from Starcoderdata.

**Comment by PeiqinSun** [comment]
so, those github-related data refer to whose meta is `RedPajamaGithub`, right? Almost "all code data" used in pre-training are sampled from Starcoderdata, which means that only the "program code tokens" of Starcoderdata are used, excluding github issues and jupyter notebooks. Is it right?

**Comment by ChaosCodes** [comment]
Github issues and jupyter notebooks in `Starcoderdata` is included
