### ISSUE TITLE
Which tokenizer settings were used to process the dataset?

### ISSUE THREAD

**Issue by awaelchli** [jzhang38/TinyLlama#76]
In the initial commit of this repository, the defaults for `Tokenizer.encode()` are (as in lit-gpt)

- `eos=False`
- `bos=False` 

[This commit](https://github.com/jzhang38/TinyLlama/commit/cfba6359541a8b6c926c48c5aea98d48f52954fd) then changed it to 

- `bos=True`
- `eos=False` 

and [another commit](https://github.com/jzhang38/TinyLlama/commit/1b6250e646bbd7298fdb4a32599696516918dfb5) later on to 

- `bos=False`
- `eos=True` 

Which of these permutations were used, or should be used, to preprocess the dataset used for pretraining tiny-llama? Note that the [preprocessing scripts](https://github.com/jzhang38/TinyLlama/blob/1f0da5366e37524e363a50dd7b8236086c00a5f3/scripts/prepare_slimpajama.py#L66) don't specify these arguments explicitly, so the defaults of the tokenizer will matter.

**Comment by carmocca** [comment]
If the HF config files are correct, it's `bos=True, eos=False`: https://huggingface.co/PY007/TinyLlama-1.1B-intermediate-step-480k-1T/blob/main/tokenizer_config.json#L2-L3

**Comment by awaelchli** [comment]
The HF config is irrelevant if the authors choose to change the defaults in the tokenizer encode function. I think only the authors can tell us with which settings they encoded the data that is used to train the model. It's not a big deal, I was just curious about which of the latter two options they chose. @jzhang38 maybe you remember?

**Comment by jzhang38** [comment]
The setup in training is bos=True eos=False. This config actually follows the default setup in lit-gpt. 
This issue was raised before. We changed it to bos=False eos=True because this is probably a better setup and benefit people using this codebase to run their own model.
