### ISSUE TITLE
How to disable flash attention?

### ISSUE THREAD

**Issue by ZhouqyCH** [jzhang38/TinyLlama#79]
Hi~My GPU does not support flash attention (V100), so I want to disable it. I noticed that if flash attention is not installed in my environment, the variable [`FlashAttention2Available`](https://github.com/jzhang38/TinyLlama/blob/main/lit_gpt/model.py#L276) controls the code from performing operator conversion. 

However, the code involving [`rotary_emb`](https://github.com/jzhang38/TinyLlama/blob/main/lit_gpt/fused_rotary_embedding.py#L39) still throws an error since I can't install it successfully. 

What tool can I use as a substitute for `rotary_emb`? Or should I simply remove this step?

**Comment by ChaosCodes** [comment]
Hi, you can install `rotary_emb` manually following [this](https://github.com/Dao-AILab/flash-attention/issues/160). But I am not sure whether it can be installed successfully on your V100. You can have a try first.

**Comment by ZhouqyCH** [comment]
> Hi, you can install `rotary_emb` manually following [this](https://github.com/Dao-AILab/flash-attention/issues/160). But I am not sure whether it can be installed successfully on your V100. You can have a try first.

Thx! I changed it manually to disable the flash attention. I can try if [it](https://github.com/Dao-AILab/flash-attention/issues/160) will work in the future.

**Comment by JerryDaHeLian** [comment]
> > Hi, you can install `rotary_emb` manually following [this](https://github.com/Dao-AILab/flash-attention/issues/160). But I am not sure whether it can be installed successfully on your V100. You can have a try first.
> 
> Thx! I changed it manually to disable the flash attention. I can try if [it](https://github.com/Dao-AILab/flash-attention/issues/160) will work in the future.

Can you pretrain tinyllama.py on v100s?
