### ISSUE TITLE
1.5T release?

### ISSUE THREAD

**Issue by binarycrayon** [jzhang38/TinyLlama#81]
Per roadmap it's due on Oct 31

**Comment by jzhang38** [comment]
We are almost [there](https://wandb.ai/lance777/lightning_logs/reports/metric-train_loss-23-09-04-23-38-15---Vmlldzo1MzA4MzIw?accessToken=5eu2sndit2mo6eqls8h38sklcgfwt660ek1f2czlgtqjv2c6tida47qm1oty8ik9). Thanks for your patience.

**Comment by Green-Sky** [comment]
Feels like the dates where predicted a bit optimistic this time. :)
