### ISSUE TITLE
Releasing TinyLlama T1.5

### ISSUE THREAD

**Issue by erfanzar** [jzhang38/TinyLlama#84]
i wanted to know when will TinyLlama 1.5T checkpoint will be released in `README.md` it's says
2023-10-31 and (Today (November 4, 2023) is 4 days after October 31, 2023)

**Comment by binarycrayon** [comment]
https://github.com/jzhang38/TinyLlama/issues/81

**Comment by Chen0x00** [comment]
I hope that nothing untoward happened again.
