### ISSUE TITLE
data mixture

### ISSUE THREAD

**Issue by NonvolatileMemory** [jzhang38/TinyLlama#93]
Hi all,

Thanks for your great work. 
I am wondering the training subset of this chinchilla-optimal model. ->这个速度可以让你可以在8个A100上用32小时训练一个chinchilla-optimial的模型(11亿参数，220亿token)
Is this part from slimpajama or you did some other data mixture to make the dataset better.
Additionally, I am also a NLP phd in singapore, supervised by Prof. jing jiang, If you wanna add my wechat pls drop me an email (cnsdunm@gmail.com).

**Comment by jzhang38** [comment]
> Is this part from slimpajama or you did some other data mixture to make the dataset better.
> 这个速度可以让你可以在8个A100上用32小时训练一个chinchilla-optimial的模型.

This is an info regarding the training throughput. It has nothing to do with the data mixture. 
If you are asking about the data mixture of TinyLlama, we train on slimpajama + starcoderdata.
