### ISSUE TITLE
Status of chat model

### ISSUE THREAD

**Issue by galleon** [jzhang38/TinyLlama#94]
It seems to me that [PY007/TinyLlama-1.1B-Chat-v0.3](https://huggingface.co/PY007/TinyLlama-1.1B-Chat-v0.3/tree/main) model weights were updated after the the 1.5T weights we issued.

I just want to check that these  `model.safetensors` weights are basically the same than  `pytorch_model.bin` or were obtained through a new fine tuning based on 1.5T.  At least the README.md seems to indicate v03 is based on 1T.

If that is the case, is there some plans to release Chat-v0.4 ?

**Comment by jzhang38** [comment]
Yes, the model.safetensors weights are basically the same as pytorch_model.bin for Chat-V0.3.

We will train and release Chat-v0.4 soon.

**Comment by jzhang38** [comment]
https://huggingface.co/TinyLlama/TinyLlama-1.1B-Chat-v0.4
